application: helloworld
version: 1
runtime: go
api_version: go1

handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /(css|img|js)/(.*)
  static_files: static/\1/\2
  upload: static/(css|img|js)/(.*)

- url: /.*
  script: _go_app
